/**
 * F3 — pure logic for trips: the passport validity rule, checklist ordering,
 * grouping and progress.
 *
 * Kept free of runtime imports so `node --test` can load it. Data access lives
 * in lib/trips.ts, which imports the Supabase client and therefore cannot.
 */
import { addMonths } from '../supabase/functions/_shared/dates.ts';

export { addMonths };

export const CHECKLIST_CATEGORIES = [
  'documents',
  'bookings',
  'money_insurance',
  'planning',
] as const;
export type ChecklistCategory = (typeof CHECKLIST_CATEGORIES)[number];

export const CHECKLIST_CATEGORY_LABELS: Record<ChecklistCategory, string> = {
  documents: 'Documents',
  bookings: 'Bookings',
  money_insurance: 'Money & insurance',
  planning: 'Planning',
};

export type ChecklistSource = 'manual' | 'auto-passport' | 'auto-entry-requirement' | 'default';

export type ChecklistItem = {
  id: string;
  trip_id: string;
  label: string;
  category: ChecklistCategory;
  status: 'todo' | 'done';
  source: ChecklistSource;
  linked_trip_item_id: string | null;
  created_at: string;
};

/**
 * F3's default checklist. Customizable, not fixed — these are seeded on trip
 * creation and the user may delete any of them.
 */
export const DEFAULT_CHECKLIST_ITEMS: { label: string; category: ChecklistCategory }[] = [
  { label: 'Book flights', category: 'bookings' },
  { label: 'Book accommodation', category: 'bookings' },
  { label: 'Arrange travel insurance', category: 'money_insurance' },
  { label: 'Arrange airport transfers', category: 'bookings' },
  { label: 'Notify bank of travel', category: 'money_insurance' },
];

/** An auto-generated item is deadline-driven and carries real urgency. */
export function isAutoGenerated(source: ChecklistSource): boolean {
  return source === 'auto-passport' || source === 'auto-entry-requirement';
}

/**
 * F3 asks for auto-generated, deadline-driven items pinned above routine
 * planning tasks, because the two carry very different urgency. Within each
 * band, outstanding work sorts above completed work — a done item is a record,
 * not a task.
 */
export function sortChecklist(items: readonly ChecklistItem[]): ChecklistItem[] {
  return [...items].sort((a, b) => {
    const autoDiff = Number(isAutoGenerated(b.source)) - Number(isAutoGenerated(a.source));
    if (autoDiff !== 0) return autoDiff;

    const statusDiff = Number(a.status === 'done') - Number(b.status === 'done');
    if (statusDiff !== 0) return statusDiff;

    const catDiff =
      CHECKLIST_CATEGORIES.indexOf(a.category) - CHECKLIST_CATEGORIES.indexOf(b.category);
    if (catDiff !== 0) return catDiff;

    return a.created_at.localeCompare(b.created_at);
  });
}

/**
 * F3 groups into categories only once a trip has more than 6–8 items. Below
 * that, headers cost more scanning than they save.
 */
export const GROUPING_THRESHOLD = 8;

export function shouldGroupChecklist(items: readonly ChecklistItem[]): boolean {
  return items.length > GROUPING_THRESHOLD;
}

export function groupChecklist(
  items: readonly ChecklistItem[]
): { category: ChecklistCategory; label: string; items: ChecklistItem[] }[] {
  const sorted = sortChecklist(items);
  const out: { category: ChecklistCategory; label: string; items: ChecklistItem[] }[] = [];
  for (const category of CHECKLIST_CATEGORIES) {
    const matching = sorted.filter((i) => i.category === category);
    if (matching.length > 0) {
      out.push({ category, label: CHECKLIST_CATEGORY_LABELS[category], items: matching });
    }
  }
  return out;
}

/** F3 wants "6 of 9 done" visible before the checklist is even opened. */
export function checklistProgress(items: readonly ChecklistItem[]): {
  done: number;
  total: number;
  label: string;
} {
  const total = items.length;
  const done = items.filter((i) => i.status === 'done').length;
  return { done, total, label: total === 0 ? 'Nothing on the list yet' : `${done} of ${total} done` };
}

// ---------------------------------------------------------------------------
// Passport validity — F3's automatic check on save
// ---------------------------------------------------------------------------

export const DEFAULT_VALIDITY_MONTHS = 6;

export type PassportLike = {
  id: string;
  traveler_id: string;
  type: string;
  expiry_date: string | null;
  country: string | null;
};

export type ValidityIssue = {
  travelerId: string;
  travelerName: string;
  /** The best passport held, or null when there is none at all. */
  documentId: string | null;
  kind: 'no-passport' | 'no-expiry-recorded' | 'expired-before-trip' | 'insufficient-validity';
  expiryDate: string | null;
  /** The date the passport needs to remain valid until. */
  requiredUntil: string;
  message: string;
};

/**
 * F3: on saving a trip, check every attendee's passport(s) against the trip
 * dates for the standard six-month rule, and say so without waiting for the
 * user to think of it.
 *
 * A traveler holding several passports (dual nationality) passes if ANY of them
 * clears — F6 later recommends which one to travel on. Only the best passport
 * is reported, so a dual national is not nagged about the one they were never
 * going to use.
 *
 * Advisory only. The six-month rule is the common case, not a universal one,
 * and the UI must say so wherever this is shown.
 */
export function checkPassportValidity(args: {
  attendees: readonly { id: string; name: string }[];
  documents: readonly PassportLike[];
  tripEndDate: string | null;
  monthsRequired?: number;
}): ValidityIssue[] {
  const { attendees, documents, tripEndDate } = args;
  const months = args.monthsRequired ?? DEFAULT_VALIDITY_MONTHS;
  if (!tripEndDate) return [];

  const requiredUntil = addMonths(tripEndDate, months);
  const issues: ValidityIssue[] = [];

  for (const attendee of attendees) {
    const passports = documents.filter(
      (d) => d.traveler_id === attendee.id && d.type === 'passport'
    );

    if (passports.length === 0) {
      issues.push({
        travelerId: attendee.id,
        travelerName: attendee.name,
        documentId: null,
        kind: 'no-passport',
        expiryDate: null,
        requiredUntil,
        message: `${attendee.name} has no passport saved.`,
      });
      continue;
    }

    const dated = passports.filter((p) => p.expiry_date);
    if (dated.length === 0) {
      issues.push({
        travelerId: attendee.id,
        travelerName: attendee.name,
        documentId: passports[0].id,
        kind: 'no-expiry-recorded',
        expiryDate: null,
        requiredUntil,
        message: `${attendee.name}'s passport has no expiry date recorded, so it can't be checked.`,
      });
      continue;
    }

    // The best passport is simply the one that expires latest.
    const best = dated.reduce((a, b) => ((a.expiry_date ?? '') >= (b.expiry_date ?? '') ? a : b));
    const expiry = best.expiry_date as string;

    if (expiry >= requiredUntil) continue; // clears the rule

    issues.push({
      travelerId: attendee.id,
      travelerName: attendee.name,
      documentId: best.id,
      kind: expiry < tripEndDate ? 'expired-before-trip' : 'insufficient-validity',
      expiryDate: expiry,
      requiredUntil,
      message:
        expiry < tripEndDate
          ? `${attendee.name}'s passport expires ${expiry}, before the trip ends.`
          : `${attendee.name}'s passport expires ${expiry}. Many countries ask for ${months} months beyond your stay — until ${requiredUntil}.`,
    });
  }

  return issues;
}

/** The checklist item text an issue should generate, if any. */
/**
 * F6's checklist label, and the pattern that recognises one.
 *
 * The pattern exists because these items were first written with source
 * 'manual' by mistake, which meant they were never deduplicated and never
 * cleaned up. Matching the label is how the sync adopts those older rows
 * instead of leaving them to accumulate — see syncEntryRequirementChecklist.
 */
export function checklistLabelForEntryIssue(travelerName: string, countryName: string): string {
  return `Sort out ${travelerName}'s passport for ${countryName}`;
}

export function looksLikeEntryRequirementItem(label: string): boolean {
  return /^Sort out .+'s passport for .+$/.test(label.trim());
}

export function checklistLabelForIssue(issue: ValidityIssue): string {
  switch (issue.kind) {
    case 'no-passport':
      return `Add ${issue.travelerName}'s passport to TripVault`;
    case 'no-expiry-recorded':
      return `Add an expiry date to ${issue.travelerName}'s passport`;
    case 'expired-before-trip':
    case 'insufficient-validity':
      return `Renew ${issue.travelerName}'s passport before travelling`;
  }
}
