/**
 * F3 — trip folder, attendees, bookings and checklist.
 *
 * Pure logic (the passport rule, checklist ordering) lives in ./tripsFormat so
 * it can be unit tested; this module is the Supabase access layer.
 */
import { supabase } from './supabase';
import {
  DEFAULT_CHECKLIST_ITEMS,
  checkPassportValidity,
  checklistLabelForIssue,
  type ChecklistCategory,
  type ChecklistItem,
  type ValidityIssue,
} from './tripsFormat';

export {
  CHECKLIST_CATEGORIES,
  CHECKLIST_CATEGORY_LABELS,
  checklistProgress,
  groupChecklist,
  isAutoGenerated,
  shouldGroupChecklist,
  sortChecklist,
} from './tripsFormat';
export type { ChecklistCategory, ChecklistItem, ValidityIssue } from './tripsFormat';

export const TRIP_ITEM_TYPES = [
  'flight',
  'accommodation',
  'car_hire',
  'transfer',
  'activity',
  'other',
] as const;
export type TripItemType = (typeof TRIP_ITEM_TYPES)[number];

export const TRIP_ITEM_TYPE_LABELS: Record<TripItemType, string> = {
  flight: 'Flight',
  accommodation: 'Accommodation',
  car_hire: 'Car hire',
  transfer: 'Transfer',
  activity: 'Activity',
  other: 'Other',
};

export type Trip = {
  id: string;
  user_id: string;
  name: string;
  destination: string | null;
  start_date: string | null;
  end_date: string | null;
  traveling_on_document_id: string | null;
  created_at: string;
};

export type TripItem = {
  id: string;
  trip_id: string | null;
  user_id: string;
  type: TripItemType;
  provider: string | null;
  confirmation_number: string | null;
  source: 'manual' | 'photo' | 'email' | 'link';
  file_path: string | null;
  external_link: string | null;
  item_date: string | null;
  amount_due: number | null;
  due_date: string | null;
  notes: string | null;
  created_at: string;
};

const TRIP_COLUMNS =
  'id, user_id, name, destination, start_date, end_date, traveling_on_document_id, created_at';
const ITEM_COLUMNS =
  'id, trip_id, user_id, type, provider, confirmation_number, source, file_path, external_link, item_date, amount_due, due_date, notes, created_at';
const CHECKLIST_COLUMNS =
  'id, trip_id, label, category, status, source, linked_trip_item_id, created_at';

async function currentUserId(): Promise<string> {
  const { data } = await supabase.auth.getUser();
  if (!data.user) throw new Error('You need to be logged in.');
  return data.user.id;
}

// --- trips -----------------------------------------------------------------

export async function listTrips(): Promise<Trip[]> {
  const { data, error } = await supabase
    .from('trips')
    .select(TRIP_COLUMNS)
    .order('start_date', { ascending: true, nullsFirst: false });
  if (error) throw new Error(error.message);
  return (data ?? []) as Trip[];
}

export async function getTrip(tripId: string): Promise<Trip | null> {
  const { data, error } = await supabase
    .from('trips')
    .select(TRIP_COLUMNS)
    .eq('id', tripId)
    .maybeSingle();
  if (error) throw new Error(error.message);
  return (data as Trip | null) ?? null;
}

export type TripInput = {
  name: string;
  destination?: string | null;
  startDate?: string | null;
  endDate?: string | null;
};

export async function createTrip(input: TripInput, attendeeIds: string[]): Promise<Trip> {
  const userId = await currentUserId();

  const { data, error } = await supabase
    .from('trips')
    .insert({
      user_id: userId,
      name: input.name.trim(),
      destination: input.destination?.trim() || null,
      start_date: input.startDate || null,
      end_date: input.endDate || null,
    })
    .select(TRIP_COLUMNS)
    .single();

  if (error) throw new Error(error.message);
  const trip = data as Trip;

  await setTripAttendees(trip.id, attendeeIds);
  await seedDefaultChecklist(trip.id);
  return trip;
}

export async function updateTrip(tripId: string, input: TripInput): Promise<Trip> {
  const { data, error } = await supabase
    .from('trips')
    .update({
      name: input.name.trim(),
      destination: input.destination?.trim() || null,
      start_date: input.startDate || null,
      end_date: input.endDate || null,
    })
    .eq('id', tripId)
    .select(TRIP_COLUMNS)
    .single();
  if (error) throw new Error(error.message);
  return data as Trip;
}

export async function deleteTrip(tripId: string): Promise<void> {
  const { error } = await supabase.from('trips').delete().eq('id', tripId);
  if (error) throw new Error(error.message);
}

// --- attendees -------------------------------------------------------------

export async function listTripAttendeeIds(tripId: string): Promise<string[]> {
  const { data, error } = await supabase
    .from('trip_travelers')
    .select('traveler_id')
    .eq('trip_id', tripId);
  if (error) throw new Error(error.message);
  return (data ?? []).map((r: { traveler_id: string }) => r.traveler_id);
}

/** Replace the attendee list wholesale — simpler than diffing, and the lists are tiny. */
export async function setTripAttendees(tripId: string, travelerIds: string[]): Promise<void> {
  const { error: delErr } = await supabase.from('trip_travelers').delete().eq('trip_id', tripId);
  if (delErr) throw new Error(delErr.message);

  if (travelerIds.length === 0) return;

  const { error } = await supabase
    .from('trip_travelers')
    .insert(travelerIds.map((traveler_id) => ({ trip_id: tripId, traveler_id })));
  if (error) throw new Error(error.message);
}

// --- checklist -------------------------------------------------------------

export async function listChecklist(tripId: string): Promise<ChecklistItem[]> {
  const { data, error } = await supabase
    .from('trip_checklist_items')
    .select(CHECKLIST_COLUMNS)
    .eq('trip_id', tripId);
  if (error) throw new Error(error.message);
  return (data ?? []) as ChecklistItem[];
}

async function seedDefaultChecklist(tripId: string): Promise<void> {
  const { error } = await supabase.from('trip_checklist_items').insert(
    DEFAULT_CHECKLIST_ITEMS.map((d) => ({
      trip_id: tripId,
      label: d.label,
      category: d.category,
      source: 'default' as const,
    }))
  );
  // A seeding failure must not lose the trip that was just created.
  if (error) console.warn('could not seed default checklist:', error.message);
}

export async function addChecklistItem(
  tripId: string,
  label: string,
  category: ChecklistCategory = 'planning'
): Promise<ChecklistItem> {
  const { data, error } = await supabase
    .from('trip_checklist_items')
    .insert({ trip_id: tripId, label: label.trim(), category, source: 'manual' })
    .select(CHECKLIST_COLUMNS)
    .single();
  if (error) throw new Error(error.message);
  return data as ChecklistItem;
}

export async function setChecklistStatus(
  itemId: string,
  status: 'todo' | 'done'
): Promise<ChecklistItem> {
  const { data, error } = await supabase
    .from('trip_checklist_items')
    .update({ status })
    .eq('id', itemId)
    .select(CHECKLIST_COLUMNS)
    .single();
  if (error) throw new Error(error.message);
  return data as ChecklistItem;
}

export async function deleteChecklistItem(itemId: string): Promise<void> {
  const { error } = await supabase.from('trip_checklist_items').delete().eq('id', itemId);
  if (error) throw new Error(error.message);
}

/**
 * F3: a checklist item should link to the real booking once made, so the
 * checklist does not become a second, disconnected source of truth. Linking
 * marks it done in the same step, since that is what linking means.
 */
export async function linkChecklistItemToTripItem(
  itemId: string,
  tripItemId: string
): Promise<ChecklistItem> {
  const { data, error } = await supabase
    .from('trip_checklist_items')
    .update({ linked_trip_item_id: tripItemId, status: 'done' })
    .eq('id', itemId)
    .select(CHECKLIST_COLUMNS)
    .single();
  if (error) throw new Error(error.message);
  return data as ChecklistItem;
}

/**
 * Run F3's automatic passport check and reflect the result on the checklist.
 *
 * Auto items are upserted rather than appended: the unique index on
 * (trip_id, source, label) means re-running on every save updates rather than
 * duplicating. Issues that have since been resolved have their auto items
 * removed, so a fixed problem stops nagging.
 */
export async function syncPassportChecklist(
  tripId: string,
  issues: readonly ValidityIssue[]
): Promise<void> {
  const wanted = issues.map(checklistLabelForIssue);

  const { data: existing } = await supabase
    .from('trip_checklist_items')
    .select('id, label')
    .eq('trip_id', tripId)
    .eq('source', 'auto-passport');

  const existingRows = (existing ?? []) as { id: string; label: string }[];

  const stale = existingRows.filter((r) => !wanted.includes(r.label));
  if (stale.length > 0) {
    await supabase
      .from('trip_checklist_items')
      .delete()
      .in('id', stale.map((r) => r.id));
  }

  const have = new Set(existingRows.map((r) => r.label));
  const toAdd = wanted.filter((label) => !have.has(label));
  if (toAdd.length > 0) {
    const { error } = await supabase.from('trip_checklist_items').insert(
      toAdd.map((label) => ({
        trip_id: tripId,
        label,
        category: 'documents' as const,
        source: 'auto-passport' as const,
      }))
    );
    if (error) console.warn('could not add passport checklist items:', error.message);
  }
}

/**
 * The whole check in one call: read the attendees' passports, apply the rule,
 * and update the checklist. Returns the issues so the UI can also say something
 * immediately, which F3 asks for on save.
 */
export async function runPassportCheck(
  tripId: string,
  attendees: readonly { id: string; name: string }[],
  tripEndDate: string | null
): Promise<ValidityIssue[]> {
  if (attendees.length === 0 || !tripEndDate) return [];

  const { data, error } = await supabase
    .from('documents')
    .select('id, traveler_id, type, expiry_date, country')
    .in('traveler_id', attendees.map((a) => a.id));

  if (error) throw new Error(error.message);

  const issues = checkPassportValidity({
    attendees,
    documents: (data ?? []) as never,
    tripEndDate,
  });

  await syncPassportChecklist(tripId, issues);
  return issues;
}

// --- bookings --------------------------------------------------------------

export async function listTripItems(tripId: string): Promise<TripItem[]> {
  const { data, error } = await supabase
    .from('trip_items')
    .select(ITEM_COLUMNS)
    .eq('trip_id', tripId)
    .order('item_date', { ascending: true, nullsFirst: false });
  if (error) throw new Error(error.message);
  return (data ?? []) as TripItem[];
}

/** F5's "Needs a trip" holding area: items that arrived with no trip attached. */
export async function listUnassignedItems(): Promise<TripItem[]> {
  const { data, error } = await supabase
    .from('trip_items')
    .select(ITEM_COLUMNS)
    .is('trip_id', null)
    .order('created_at', { ascending: false });
  if (error) throw new Error(error.message);
  return (data ?? []) as TripItem[];
}

export type TripItemInput = {
  type: TripItemType;
  provider?: string | null;
  confirmationNumber?: string | null;
  itemDate?: string | null;
  amountDue?: number | null;
  dueDate?: string | null;
  externalLink?: string | null;
  notes?: string | null;
};

export async function createTripItem(
  tripId: string | null,
  input: TripItemInput,
  source: TripItem['source'] = 'manual'
): Promise<TripItem> {
  const userId = await currentUserId();
  const { data, error } = await supabase
    .from('trip_items')
    .insert({
      trip_id: tripId,
      user_id: userId,
      type: input.type,
      provider: input.provider?.trim() || null,
      confirmation_number: input.confirmationNumber?.trim() || null,
      source,
      item_date: input.itemDate || null,
      amount_due: input.amountDue ?? null,
      due_date: input.dueDate || null,
      external_link: input.externalLink?.trim() || null,
      notes: input.notes?.trim() || null,
    })
    .select(ITEM_COLUMNS)
    .single();

  if (error) throw new Error(error.message);
  return data as TripItem;
}

export async function assignItemToTrip(itemId: string, tripId: string): Promise<TripItem> {
  const { data, error } = await supabase
    .from('trip_items')
    .update({ trip_id: tripId })
    .eq('id', itemId)
    .select(ITEM_COLUMNS)
    .single();
  if (error) throw new Error(error.message);
  return data as TripItem;
}

export async function deleteTripItem(itemId: string): Promise<void> {
  const { error } = await supabase.from('trip_items').delete().eq('id', itemId);
  if (error) throw new Error(error.message);
}
