import React, { useCallback, useEffect, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import type { Traveler } from '../types/traveler';
import {
  CHECKLIST_CATEGORY_LABELS,
  TRIP_ITEM_TYPES,
  TRIP_ITEM_TYPE_LABELS,
  addChecklistItem,
  checklistProgress,
  createTripItem,
  deleteChecklistItem,
  deleteTripItem,
  groupChecklist,
  isAutoGenerated,
  linkChecklistItemToTripItem,
  listChecklist,
  listTripAttendeeIds,
  listTripItems,
  runPassportCheck,
  setChecklistStatus,
  shouldGroupChecklist,
  sortChecklist,
  type ChecklistItem,
  type Trip,
  type TripItem,
  type TripItemType,
  type ValidityIssue,
} from '../lib/trips';
import {
  ENTRY_REQUIREMENTS_UNAVAILABLE_MESSAGE,
  ENTRY_REQUIREMENT_UNKNOWN_MESSAGE,
  disclaimerFor,
  isEntryRequirementCheckAvailable,
  runEntryRequirementCheck,
} from '../lib/entryRequirements';

/**
 * F3 — one trip: who's going, what still needs organizing, and every booking.
 */
export default function TripDetailScreen({
  trip,
  travelers,
  onBack,
}: {
  trip: Trip;
  travelers: Traveler[];
  onBack: () => void;
}) {
  const [attendeeIds, setAttendeeIds] = useState<string[]>([]);
  const [checklist, setChecklist] = useState<ChecklistItem[]>([]);
  const [items, setItems] = useState<TripItem[]>([]);
  const [issues, setIssues] = useState<ValidityIssue[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [newLabel, setNewLabel] = useState('');
  const [addingItem, setAddingItem] = useState(false);
  const [checkingEntry, setCheckingEntry] = useState(false);

  const attendees = travelers.filter((t) => attendeeIds.includes(t.id));

  const refresh = useCallback(async () => {
    setLoading(true);
    try {
      const [ids, cl, its] = await Promise.all([
        listTripAttendeeIds(trip.id),
        listChecklist(trip.id),
        listTripItems(trip.id),
      ]);
      setAttendeeIds(ids);
      setItems(its);

      // F3: the passport check runs on open as well as on save, so a document
      // that expired since the trip was created still surfaces.
      const named = travelers
        .filter((t) => ids.includes(t.id))
        .map((t) => ({ id: t.id, name: t.name }));
      const found = await runPassportCheck(trip.id, named, trip.end_date);
      setIssues(found);

      // Re-read after the check, which may have added or removed auto items.
      setChecklist(found.length > 0 || cl.length > 0 ? await listChecklist(trip.id) : cl);
      setError(null);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setLoading(false);
    }
  }, [trip.id, trip.end_date, travelers]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  /**
   * F3's soft integration point with F6.
   *
   * Availability is probed, not assumed. Before Phase 8 this took the "not
   * available yet" path; now that F6's reference table exists the same code
   * runs the real check, with no change on this side -- which is what the soft
   * integration was for.
   */
  async function checkEntryRequirements() {
    setCheckingEntry(true);
    try {
      if (!(await isEntryRequirementCheckAvailable())) {
        Alert.alert('Entry requirements', ENTRY_REQUIREMENTS_UNAVAILABLE_MESSAGE);
        return;
      }

      const country = (trip.destination ?? '').trim();
      if (!country) {
        Alert.alert(
          'Entry requirements',
          "Add a destination to this trip first — the rule depends on where you're going."
        );
        return;
      }

      const named = attendees.map((t) => ({ id: t.id, name: t.name }));
      const { requirement, results } = await runEntryRequirementCheck({
        destinationCountry: country,
        attendees: named,
        startDate: trip.start_date,
        endDate: trip.end_date,
      });

      if (!requirement) {
        Alert.alert('Entry requirements', ENTRY_REQUIREMENT_UNKNOWN_MESSAGE);
        return;
      }

      const lines = results.map((r) =>
        r.problem ? `• ${r.problem}` : `• ${r.check?.recommendationReason ?? ''}`
      );

      Alert.alert(
        `${requirement.countryName} — passport validity`,
        `${lines.join('\n\n')}\n\n${disclaimerFor(requirement)}`
      );

      // F3: anything flagged becomes a checklist item, so it is not just an
      // alert the user dismisses and forgets.
      const failing = results.filter((r) => r.problem || r.check?.anyClears === false);
      for (const r of failing) {
        await addChecklistItem(
          trip.id,
          `Sort out ${r.travelerName}'s passport for ${requirement.countryName}`,
          'documents'
        ).catch(() => undefined);
      }
      if (failing.length > 0) setChecklist(await listChecklist(trip.id));
    } catch (e) {
      Alert.alert(
        'Entry requirements',
        e instanceof Error ? e.message : ENTRY_REQUIREMENTS_UNAVAILABLE_MESSAGE
      );
    } finally {
      setCheckingEntry(false);
    }
  }

  async function toggle(item: ChecklistItem) {
    try {
      await setChecklistStatus(item.id, item.status === 'done' ? 'todo' : 'done');
      setChecklist(await listChecklist(trip.id));
    } catch (e) {
      Alert.alert('Could not update', e instanceof Error ? e.message : String(e));
    }
  }

  async function addItem() {
    if (!newLabel.trim()) return;
    try {
      await addChecklistItem(trip.id, newLabel);
      setNewLabel('');
      setChecklist(await listChecklist(trip.id));
    } catch (e) {
      Alert.alert('Could not add', e instanceof Error ? e.message : String(e));
    }
  }

  function confirmDeleteChecklist(item: ChecklistItem) {
    Alert.alert('Remove item', `Remove "${item.label}"?`, [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Remove',
        style: 'destructive',
        onPress: async () => {
          await deleteChecklistItem(item.id).catch(() => undefined);
          setChecklist(await listChecklist(trip.id));
        },
      },
    ]);
  }

  const progress = checklistProgress(checklist);
  const grouped = shouldGroupChecklist(checklist);

  return (
    <View style={styles.container}>
      <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled">
        <Pressable onPress={onBack} hitSlop={8}>
          <Text style={styles.back}>‹ Trips</Text>
        </Pressable>

        <Text style={styles.heading}>{trip.name}</Text>
        <Text style={styles.meta}>
          {trip.destination ? `${trip.destination} · ` : ''}
          {trip.start_date && trip.end_date
            ? `${trip.start_date} → ${trip.end_date}`
            : 'Dates not set'}
        </Text>
        <Text style={styles.progress}>{progress.label}</Text>

        {error && <Text style={styles.error}>{error}</Text>}
        {loading && <ActivityIndicator style={styles.spinner} />}

        {attendees.length > 0 && (
          <Text style={styles.meta}>Travelling: {attendees.map((a) => a.name).join(', ')}</Text>
        )}

        {/* F3: passport problems are surfaced without waiting to be asked. */}
        {issues.length > 0 && (
          <View style={styles.warnBox}>
            <Text style={styles.warnTitle}>Passport check</Text>
            {issues.map((i) => (
              <Text key={i.travelerId} style={styles.warnBody}>
                • {i.message}
              </Text>
            ))}
            <Text style={styles.advisory}>
              Advisory only — rules vary by destination. Verify with the relevant embassy or
              consulate.
            </Text>
          </View>
        )}

        <Pressable
          style={[styles.secondary, checkingEntry && styles.disabled]}
          onPress={checkEntryRequirements}
          disabled={checkingEntry}
        >
          {checkingEntry ? (
            <ActivityIndicator />
          ) : (
            <Text style={styles.secondaryText}>Check entry requirements</Text>
          )}
        </Pressable>

        <Text style={styles.section}>Checklist</Text>

        {grouped
          ? groupChecklist(checklist).map((g) => (
              <View key={g.category} style={styles.group}>
                <Text style={styles.groupLabel}>{g.label}</Text>
                {g.items.map((item) => (
                  <ChecklistRow
                    key={item.id}
                    item={item}
                    onToggle={() => toggle(item)}
                    onDelete={() => confirmDeleteChecklist(item)}
                  />
                ))}
              </View>
            ))
          : sortChecklist(checklist).map((item) => (
              <ChecklistRow
                key={item.id}
                item={item}
                onToggle={() => toggle(item)}
                onDelete={() => confirmDeleteChecklist(item)}
              />
            ))}

        <View style={styles.addRow}>
          <TextInput
            style={[styles.input, styles.addInput]}
            value={newLabel}
            onChangeText={setNewLabel}
            placeholder="Add something to the list"
            onSubmitEditing={addItem}
          />
          <Pressable style={styles.addBtn} onPress={addItem}>
            <Text style={styles.addBtnText}>Add</Text>
          </Pressable>
        </View>

        <Text style={styles.section}>Bookings</Text>
        {items.length === 0 && (
          <Text style={styles.empty}>
            Nothing booked yet. Add flights, hotels and transfers as you organise them.
          </Text>
        )}
        {items.map((it) => (
          <Pressable
            key={it.id}
            style={styles.card}
            onLongPress={() =>
              Alert.alert('Remove booking', `Remove ${it.provider ?? 'this booking'}?`, [
                { text: 'Cancel', style: 'cancel' },
                {
                  text: 'Remove',
                  style: 'destructive',
                  onPress: async () => {
                    await deleteTripItem(it.id).catch(() => undefined);
                    setItems(await listTripItems(trip.id));
                  },
                },
              ])
            }
          >
            <Text style={styles.cardTitle}>
              {TRIP_ITEM_TYPE_LABELS[it.type]}
              {it.provider ? ` · ${it.provider}` : ''}
            </Text>
            {it.confirmation_number ? (
              <Text style={styles.cardMeta}>Ref {it.confirmation_number}</Text>
            ) : null}
            {it.item_date ? <Text style={styles.cardMeta}>{it.item_date.slice(0, 10)}</Text> : null}
          </Pressable>
        ))}

        {addingItem ? (
          <BookingForm
            tripId={trip.id}
            checklist={checklist}
            onCancel={() => setAddingItem(false)}
            onSaved={async () => {
              setAddingItem(false);
              setItems(await listTripItems(trip.id));
              setChecklist(await listChecklist(trip.id));
            }}
          />
        ) : (
          <Pressable style={styles.secondary} onPress={() => setAddingItem(true)}>
            <Text style={styles.secondaryText}>Add booking</Text>
          </Pressable>
        )}
      </ScrollView>
    </View>
  );
}

function ChecklistRow({
  item,
  onToggle,
  onDelete,
}: {
  item: ChecklistItem;
  onToggle: () => void;
  onDelete: () => void;
}) {
  const auto = isAutoGenerated(item.source);
  return (
    <Pressable
      style={[styles.checkRow, auto && styles.checkRowAuto]}
      onPress={onToggle}
      onLongPress={onDelete}
    >
      <View style={[styles.box, item.status === 'done' && styles.boxOn]}>
        {item.status === 'done' && <Text style={styles.tick}>✓</Text>}
      </View>
      <View style={styles.checkMain}>
        <Text style={[styles.checkLabel, item.status === 'done' && styles.checkLabelDone]}>
          {item.label}
        </Text>
        <Text style={styles.checkMeta}>
          {auto ? 'Needs attention · ' : ''}
          {CHECKLIST_CATEGORY_LABELS[item.category]}
          {item.linked_trip_item_id ? ' · linked to a booking' : ''}
        </Text>
      </View>
    </Pressable>
  );
}

function BookingForm({
  tripId,
  checklist,
  onSaved,
  onCancel,
}: {
  tripId: string;
  checklist: ChecklistItem[];
  onSaved: () => void;
  onCancel: () => void;
}) {
  const [type, setType] = useState<TripItemType>('flight');
  const [provider, setProvider] = useState('');
  const [confirmationNumber, setConfirmationNumber] = useState('');
  const [linkTo, setLinkTo] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const linkable = checklist.filter((c) => c.status === 'todo' && !c.linked_trip_item_id);

  async function save() {
    setBusy(true);
    try {
      const created = await createTripItem(tripId, { type, provider, confirmationNumber });
      // F3: linking marks the checklist item done, so the list does not become
      // a second source of truth beside the real bookings.
      if (linkTo) await linkChecklistItemToTripItem(linkTo, created.id);
      onSaved();
    } catch (e) {
      Alert.alert('Could not save', e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  }

  return (
    <View style={styles.formBox}>
      <Text style={styles.section}>Add booking</Text>

      <View style={styles.chips}>
        {TRIP_ITEM_TYPES.map((t) => (
          <Pressable
            key={t}
            style={[styles.chip, t === type && styles.chipOn]}
            onPress={() => setType(t)}
            disabled={busy}
          >
            <Text style={[styles.chipText, t === type && styles.chipTextOn]}>
              {TRIP_ITEM_TYPE_LABELS[t]}
            </Text>
          </Pressable>
        ))}
      </View>

      <TextInput
        style={styles.input}
        value={provider}
        onChangeText={setProvider}
        placeholder="Provider, e.g. Qantas"
        editable={!busy}
      />
      <TextInput
        style={styles.input}
        value={confirmationNumber}
        onChangeText={setConfirmationNumber}
        placeholder="Confirmation number"
        autoCapitalize="characters"
        editable={!busy}
      />

      {linkable.length > 0 && (
        <>
          <Text style={styles.label}>Tick off a checklist item (optional)</Text>
          <View style={styles.chips}>
            {linkable.map((c) => (
              <Pressable
                key={c.id}
                style={[styles.chip, linkTo === c.id && styles.chipOn]}
                onPress={() => setLinkTo(linkTo === c.id ? null : c.id)}
                disabled={busy}
              >
                <Text style={[styles.chipText, linkTo === c.id && styles.chipTextOn]}>
                  {c.label}
                </Text>
              </Pressable>
            ))}
          </View>
        </>
      )}

      <Pressable style={[styles.primaryInline, busy && styles.disabled]} onPress={save} disabled={busy}>
        {busy ? <ActivityIndicator color="#fff" /> : <Text style={styles.primaryText}>Save booking</Text>}
      </Pressable>
      <Pressable onPress={onCancel} disabled={busy} hitSlop={8}>
        <Text style={styles.cancel}>Cancel</Text>
      </Pressable>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  scroll: { padding: 24, gap: 10, paddingBottom: 48 },
  back: { color: '#1B6EF3', fontSize: 15, fontWeight: '600' },
  heading: { fontSize: 22, fontWeight: '700', marginTop: 4 },
  meta: { fontSize: 14, color: '#666' },
  progress: { fontSize: 15, fontWeight: '600', color: '#1B6EF3' },
  section: { fontSize: 17, fontWeight: '700', marginTop: 18 },
  error: { color: '#C4342B', fontSize: 14 },
  empty: { color: '#666', fontSize: 15, lineHeight: 21 },
  spinner: { marginTop: 12 },
  warnBox: {
    backgroundColor: '#FFF4E5',
    borderColor: '#F0B429',
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    gap: 4,
    marginTop: 8,
  },
  warnTitle: { fontWeight: '700', color: '#7A4E00' },
  warnBody: { color: '#7A4E00', fontSize: 14, lineHeight: 20 },
  advisory: { color: '#7A4E00', fontSize: 12, fontStyle: 'italic', marginTop: 4, lineHeight: 17 },
  group: { gap: 6, marginTop: 10 },
  groupLabel: {
    fontSize: 13,
    color: '#666',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontWeight: '600',
  },
  checkRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    borderWidth: 1,
    borderColor: '#E4E4E4',
    borderRadius: 8,
    padding: 12,
    marginTop: 6,
  },
  checkRowAuto: { borderColor: '#F0B429', backgroundColor: '#FFFCF5' },
  box: {
    width: 24,
    height: 24,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#9A9A9A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  boxOn: { backgroundColor: '#1B6EF3', borderColor: '#1B6EF3' },
  tick: { color: '#fff', fontSize: 15, fontWeight: '700' },
  checkMain: { flex: 1, gap: 2 },
  checkLabel: { fontSize: 15 },
  checkLabelDone: { textDecorationLine: 'line-through', color: '#888' },
  checkMeta: { fontSize: 12, color: '#777' },
  addRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
  addInput: { flex: 1 },
  addBtn: {
    backgroundColor: '#1B6EF3',
    borderRadius: 8,
    paddingHorizontal: 18,
    justifyContent: 'center',
  },
  addBtnText: { color: '#fff', fontWeight: '600' },
  card: {
    borderWidth: 1,
    borderColor: '#E4E4E4',
    borderRadius: 10,
    padding: 14,
    gap: 4,
    marginTop: 6,
  },
  cardTitle: { fontSize: 16, fontWeight: '600' },
  cardMeta: { fontSize: 14, color: '#666' },
  formBox: {
    borderWidth: 1,
    borderColor: '#E4E4E4',
    borderRadius: 10,
    padding: 14,
    gap: 10,
    marginTop: 10,
  },
  label: {
    fontSize: 13,
    color: '#666',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: 4,
  },
  input: {
    borderWidth: 1,
    borderColor: '#D0D0D0',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
  },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    borderWidth: 1,
    borderColor: '#D0D0D0',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  chipOn: { backgroundColor: '#1B6EF3', borderColor: '#1B6EF3' },
  chipText: { fontSize: 14, color: '#333' },
  chipTextOn: { color: '#fff', fontWeight: '600' },
  secondary: {
    borderWidth: 1,
    borderColor: '#1B6EF3',
    borderRadius: 8,
    paddingVertical: 13,
    alignItems: 'center',
    marginTop: 10,
  },
  secondaryText: { color: '#1B6EF3', fontSize: 15, fontWeight: '600' },
  primaryInline: {
    backgroundColor: '#1B6EF3',
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
  },
  disabled: { opacity: 0.6 },
  primaryText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  cancel: { textAlign: 'center', color: '#1B6EF3', marginTop: 2 },
});
